/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as UsersListRouteImport } from './routes/users/list'
import { Route as StaffListRouteImport } from './routes/staff/list'
import { Route as StaffCreateRouteImport } from './routes/staff/create'
import { Route as UsersUserIdIndexRouteImport } from './routes/users/$userId/index'
import { Route as StaffStaffIdIndexRouteImport } from './routes/staff/$staffId/index'
import { Route as UsersUserIdEditRouteImport } from './routes/users/$userId/edit'
import { Route as StaffStaffIdEditRouteImport } from './routes/staff/$staffId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersListRoute = UsersListRouteImport.update({
  id: '/users/list',
  path: '/users/list',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffListRoute = StaffListRouteImport.update({
  id: '/staff/list',
  path: '/staff/list',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCreateRoute = StaffCreateRouteImport.update({
  id: '/staff/create',
  path: '/staff/create',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffIdIndexRoute = StaffStaffIdIndexRouteImport.update({
  id: '/staff/$staffId/',
  path: '/staff/$staffId/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdEditRoute = UsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffIdEditRoute = StaffStaffIdEditRouteImport.update({
  id: '/staff/$staffId/edit',
  path: '/staff/$staffId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/staff/create': typeof StaffCreateRoute
  '/staff/list': typeof StaffListRoute
  '/users/list': typeof UsersListRoute
  '/staff': typeof StaffIndexRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/staff/$staffId': typeof StaffStaffIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/staff/create': typeof StaffCreateRoute
  '/staff/list': typeof StaffListRoute
  '/users/list': typeof UsersListRoute
  '/staff': typeof StaffIndexRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/staff/$staffId': typeof StaffStaffIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/staff/create': typeof StaffCreateRoute
  '/staff/list': typeof StaffListRoute
  '/users/list': typeof UsersListRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/staff/$staffId/': typeof StaffStaffIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/staff/create'
    | '/staff/list'
    | '/users/list'
    | '/staff'
    | '/staff/$staffId/edit'
    | '/users/$userId/edit'
    | '/staff/$staffId'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/staff/create'
    | '/staff/list'
    | '/users/list'
    | '/staff'
    | '/staff/$staffId/edit'
    | '/users/$userId/edit'
    | '/staff/$staffId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/staff/create'
    | '/staff/list'
    | '/users/list'
    | '/staff/'
    | '/staff/$staffId/edit'
    | '/users/$userId/edit'
    | '/staff/$staffId/'
    | '/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StaffCreateRoute: typeof StaffCreateRoute
  StaffListRoute: typeof StaffListRoute
  UsersListRoute: typeof UsersListRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffStaffIdEditRoute: typeof StaffStaffIdEditRoute
  UsersUserIdEditRoute: typeof UsersUserIdEditRoute
  StaffStaffIdIndexRoute: typeof StaffStaffIdIndexRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/list': {
      id: '/users/list'
      path: '/users/list'
      fullPath: '/users/list'
      preLoaderRoute: typeof UsersListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/list': {
      id: '/staff/list'
      path: '/staff/list'
      fullPath: '/staff/list'
      preLoaderRoute: typeof StaffListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/create': {
      id: '/staff/create'
      path: '/staff/create'
      fullPath: '/staff/create'
      preLoaderRoute: typeof StaffCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$staffId/': {
      id: '/staff/$staffId/'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof StaffStaffIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/edit': {
      id: '/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof UsersUserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$staffId/edit': {
      id: '/staff/$staffId/edit'
      path: '/staff/$staffId/edit'
      fullPath: '/staff/$staffId/edit'
      preLoaderRoute: typeof StaffStaffIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StaffCreateRoute: StaffCreateRoute,
  StaffListRoute: StaffListRoute,
  UsersListRoute: UsersListRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffStaffIdEditRoute: StaffStaffIdEditRoute,
  UsersUserIdEditRoute: UsersUserIdEditRoute,
  StaffStaffIdIndexRoute: StaffStaffIdIndexRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
