/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalEntriesIndexRouteImport } from './routes/journal-entries/index'
import { Route as GlAccountsIndexRouteImport } from './routes/gl-accounts/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CreateEntryIndexRouteImport } from './routes/create-entry/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalEntriesIndexRoute = JournalEntriesIndexRouteImport.update({
  id: '/journal-entries/',
  path: '/journal-entries/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlAccountsIndexRoute = GlAccountsIndexRouteImport.update({
  id: '/gl-accounts/',
  path: '/gl-accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateEntryIndexRoute = CreateEntryIndexRouteImport.update({
  id: '/create-entry/',
  path: '/create-entry/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-entry': typeof CreateEntryIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/gl-accounts': typeof GlAccountsIndexRoute
  '/journal-entries': typeof JournalEntriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-entry': typeof CreateEntryIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/gl-accounts': typeof GlAccountsIndexRoute
  '/journal-entries': typeof JournalEntriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-entry/': typeof CreateEntryIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/gl-accounts/': typeof GlAccountsIndexRoute
  '/journal-entries/': typeof JournalEntriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-entry'
    | '/dashboard'
    | '/gl-accounts'
    | '/journal-entries'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-entry' | '/dashboard' | '/gl-accounts' | '/journal-entries'
  id:
    | '__root__'
    | '/'
    | '/create-entry/'
    | '/dashboard/'
    | '/gl-accounts/'
    | '/journal-entries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateEntryIndexRoute: typeof CreateEntryIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  GlAccountsIndexRoute: typeof GlAccountsIndexRoute
  JournalEntriesIndexRoute: typeof JournalEntriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal-entries/': {
      id: '/journal-entries/'
      path: '/journal-entries'
      fullPath: '/journal-entries'
      preLoaderRoute: typeof JournalEntriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gl-accounts/': {
      id: '/gl-accounts/'
      path: '/gl-accounts'
      fullPath: '/gl-accounts'
      preLoaderRoute: typeof GlAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-entry/': {
      id: '/create-entry/'
      path: '/create-entry'
      fullPath: '/create-entry'
      preLoaderRoute: typeof CreateEntryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateEntryIndexRoute: CreateEntryIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  GlAccountsIndexRoute: GlAccountsIndexRoute,
  JournalEntriesIndexRoute: JournalEntriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
