/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettlementRouteImport } from './routes/settlement'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduledPaymentsRouteImport } from './routes/scheduled-payments'
import { Route as OrderResolutionRouteImport } from './routes/order-resolution'
import { Route as MarketSettingsRouteImport } from './routes/market-settings'
import { Route as LpPerformanceRouteImport } from './routes/lp-performance'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as IncomeHistoryRouteImport } from './routes/income-history'
import { Route as IncomeCalendarRouteImport } from './routes/income-calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateAssetRouteImport } from './routes/create-asset'
import { Route as PaymentDlqRouteImport } from './routes/payment-dlq'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PricingAssetIdRouteImport } from './routes/pricing.$assetId'
import { Route as PaymentResultsPaymentIdRouteImport } from './routes/payment-results.$paymentId'
import { Route as AssetDetailsAssetIdRouteImport } from './routes/asset-details.$assetId'

const SettlementRoute = SettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledPaymentsRoute = ScheduledPaymentsRouteImport.update({
  id: '/scheduled-payments',
  path: '/scheduled-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderResolutionRoute = OrderResolutionRouteImport.update({
  id: '/order-resolution',
  path: '/order-resolution',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketSettingsRoute = MarketSettingsRouteImport.update({
  id: '/market-settings',
  path: '/market-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LpPerformanceRoute = LpPerformanceRouteImport.update({
  id: '/lp-performance',
  path: '/lp-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeCalendarRoute = IncomeCalendarRouteImport.update({
  id: '/income-calendar',
  path: '/income-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeHistoryRoute = IncomeHistoryRouteImport.update({
  id: '/income-history',
  path: '/income-history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAssetRoute = CreateAssetRouteImport.update({
  id: '/create-asset',
  path: '/create-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentDlqRoute = PaymentDlqRouteImport.update({
  id: '/payment-dlq',
  path: '/payment-dlq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingAssetIdRoute = PricingAssetIdRouteImport.update({
  id: '/pricing/$assetId',
  path: '/pricing/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResultsPaymentIdRoute = PaymentResultsPaymentIdRouteImport.update({
  id: '/payment-results/$paymentId',
  path: '/payment-results/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetDetailsAssetIdRoute = AssetDetailsAssetIdRouteImport.update({
  id: '/asset-details/$assetId',
  path: '/asset-details/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/audit-log': typeof AuditLogRoute
  '/payment-dlq': typeof PaymentDlqRoute
  '/create-asset': typeof CreateAssetRoute
  '/dashboard': typeof DashboardRoute
  '/income-calendar': typeof IncomeCalendarRoute
  '/income-history': typeof IncomeHistoryRoute
  '/inventory': typeof InventoryRoute
  '/portfolio': typeof PortfolioRoute
  '/lp-performance': typeof LpPerformanceRoute
  '/market-settings': typeof MarketSettingsRoute
  '/order-resolution': typeof OrderResolutionRoute
  '/scheduled-payments': typeof ScheduledPaymentsRoute
  '/settings': typeof SettingsRoute
  '/settlement': typeof SettlementRoute
  '/asset-details/$assetId': typeof AssetDetailsAssetIdRoute
  '/payment-results/$paymentId': typeof PaymentResultsPaymentIdRoute
  '/pricing/$assetId': typeof PricingAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/audit-log': typeof AuditLogRoute
  '/payment-dlq': typeof PaymentDlqRoute
  '/create-asset': typeof CreateAssetRoute
  '/dashboard': typeof DashboardRoute
  '/income-calendar': typeof IncomeCalendarRoute
  '/income-history': typeof IncomeHistoryRoute
  '/income-history': typeof IncomeHistoryRoute
  '/inventory': typeof InventoryRoute
  '/portfolio': typeof PortfolioRoute
  '/lp-performance': typeof LpPerformanceRoute
  '/market-settings': typeof MarketSettingsRoute
  '/order-resolution': typeof OrderResolutionRoute
  '/scheduled-payments': typeof ScheduledPaymentsRoute
  '/settings': typeof SettingsRoute
  '/settlement': typeof SettlementRoute
  '/asset-details/$assetId': typeof AssetDetailsAssetIdRoute
  '/payment-results/$paymentId': typeof PaymentResultsPaymentIdRoute
  '/pricing/$assetId': typeof PricingAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/audit-log': typeof AuditLogRoute
  '/payment-dlq': typeof PaymentDlqRoute
  '/create-asset': typeof CreateAssetRoute
  '/dashboard': typeof DashboardRoute
  '/income-calendar': typeof IncomeCalendarRoute
  '/income-history': typeof IncomeHistoryRoute
  '/income-history': typeof IncomeHistoryRoute
  '/inventory': typeof InventoryRoute
  '/portfolio': typeof PortfolioRoute
  '/lp-performance': typeof LpPerformanceRoute
  '/market-settings': typeof MarketSettingsRoute
  '/order-resolution': typeof OrderResolutionRoute
  '/scheduled-payments': typeof ScheduledPaymentsRoute
  '/settings': typeof SettingsRoute
  '/settlement': typeof SettlementRoute
  '/asset-details/$assetId': typeof AssetDetailsAssetIdRoute
  '/payment-results/$paymentId': typeof PaymentResultsPaymentIdRoute
  '/pricing/$assetId': typeof PricingAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/audit-log'
    | '/payment-dlq'
    | '/create-asset'
    | '/dashboard'
    | '/income-calendar'
    | '/income-history'
    | '/inventory'
    | '/lp-performance'
    | '/market-settings'
    | '/order-resolution'
    | '/portfolio'
    | '/scheduled-payments'
    | '/settings'
    | '/settlement'
    | '/asset-details/$assetId'
    | '/payment-results/$paymentId'
    | '/pricing/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/audit-log'
    | '/payment-dlq'
    | '/create-asset'
    | '/dashboard'
    | '/income-calendar'
    | '/income-history'
    | '/inventory'
    | '/lp-performance'
    | '/market-settings'
    | '/order-resolution'
    | '/portfolio'
    | '/scheduled-payments'
    | '/settings'
    | '/settlement'
    | '/asset-details/$assetId'
    | '/payment-results/$paymentId'
    | '/pricing/$assetId'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/audit-log'
    | '/payment-dlq'
    | '/create-asset'
    | '/dashboard'
    | '/income-calendar'
    | '/income-history'
    | '/inventory'
    | '/lp-performance'
    | '/market-settings'
    | '/order-resolution'
    | '/portfolio'
    | '/scheduled-payments'
    | '/settings'
    | '/settlement'
    | '/asset-details/$assetId'
    | '/payment-results/$paymentId'
    | '/pricing/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AuditLogRoute: typeof AuditLogRoute
  PaymentDlqRoute: typeof PaymentDlqRoute
  CreateAssetRoute: typeof CreateAssetRoute
  DashboardRoute: typeof DashboardRoute
  IncomeCalendarRoute: typeof IncomeCalendarRoute
  IncomeHistoryRoute: typeof IncomeHistoryRoute
  InventoryRoute: typeof InventoryRoute
  PortfolioRoute: typeof PortfolioRoute
  LpPerformanceRoute: typeof LpPerformanceRoute
  MarketSettingsRoute: typeof MarketSettingsRoute
  OrderResolutionRoute: typeof OrderResolutionRoute
  ScheduledPaymentsRoute: typeof ScheduledPaymentsRoute
  SettingsRoute: typeof SettingsRoute
  SettlementRoute: typeof SettlementRoute
  AssetDetailsAssetIdRoute: typeof AssetDetailsAssetIdRoute
  PaymentResultsPaymentIdRoute: typeof PaymentResultsPaymentIdRoute
  PricingAssetIdRoute: typeof PricingAssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settlement': {
      id: '/settlement'
      path: '/settlement'
      fullPath: '/settlement'
      preLoaderRoute: typeof SettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled-payments': {
      id: '/scheduled-payments'
      path: '/scheduled-payments'
      fullPath: '/scheduled-payments'
      preLoaderRoute: typeof ScheduledPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-resolution': {
      id: '/order-resolution'
      path: '/order-resolution'
      fullPath: '/order-resolution'
      preLoaderRoute: typeof OrderResolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-settings': {
      id: '/market-settings'
      path: '/market-settings'
      fullPath: '/market-settings'
      preLoaderRoute: typeof MarketSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp-performance': {
      id: '/lp-performance'
      path: '/lp-performance'
      fullPath: '/lp-performance'
      preLoaderRoute: typeof LpPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-calendar': {
      id: '/income-calendar'
      path: '/income-calendar'
      fullPath: '/income-calendar'
      preLoaderRoute: typeof IncomeCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-history': {
      id: '/income-history'
      path: '/income-history'
      fullPath: '/income-history'
      preLoaderRoute: typeof IncomeHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-asset': {
      id: '/create-asset'
      path: '/create-asset'
      fullPath: '/create-asset'
      preLoaderRoute: typeof CreateAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-dlq': {
      id: '/payment-dlq'
      path: '/payment-dlq'
      fullPath: '/payment-dlq'
      preLoaderRoute: typeof PaymentDlqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/$assetId': {
      id: '/pricing/$assetId'
      path: '/pricing/$assetId'
      fullPath: '/pricing/$assetId'
      preLoaderRoute: typeof PricingAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-results/$paymentId': {
      id: '/payment-results/$paymentId'
      path: '/payment-results/$paymentId'
      fullPath: '/payment-results/$paymentId'
      preLoaderRoute: typeof PaymentResultsPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-details/$assetId': {
      id: '/asset-details/$assetId'
      path: '/asset-details/$assetId'
      fullPath: '/asset-details/$assetId'
      preLoaderRoute: typeof AssetDetailsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AuditLogRoute: AuditLogRoute,
  PaymentDlqRoute: PaymentDlqRoute,
  CreateAssetRoute: CreateAssetRoute,
  DashboardRoute: DashboardRoute,
  IncomeCalendarRoute: IncomeCalendarRoute,
  IncomeHistoryRoute: IncomeHistoryRoute,
  InventoryRoute: InventoryRoute,
  PortfolioRoute: PortfolioRoute,
  LpPerformanceRoute: LpPerformanceRoute,
  MarketSettingsRoute: MarketSettingsRoute,
  OrderResolutionRoute: OrderResolutionRoute,
  ScheduledPaymentsRoute: ScheduledPaymentsRoute,
  SettingsRoute: SettingsRoute,
  SettlementRoute: SettlementRoute,
  AssetDetailsAssetIdRoute: AssetDetailsAssetIdRoute,
  PaymentResultsPaymentIdRoute: PaymentResultsPaymentIdRoute,
  PricingAssetIdRoute: PricingAssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
