/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OrderResolutionRouteImport } from './routes/order-resolution'
import { Route as MarketSettingsRouteImport } from './routes/market-settings'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateAssetRouteImport } from './routes/create-asset'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PricingAssetIdRouteImport } from './routes/pricing.$assetId'
import { Route as AssetDetailsAssetIdRouteImport } from './routes/asset-details.$assetId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderResolutionRoute = OrderResolutionRouteImport.update({
  id: '/order-resolution',
  path: '/order-resolution',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketSettingsRoute = MarketSettingsRouteImport.update({
  id: '/market-settings',
  path: '/market-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAssetRoute = CreateAssetRouteImport.update({
  id: '/create-asset',
  path: '/create-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingAssetIdRoute = PricingAssetIdRouteImport.update({
  id: '/pricing/$assetId',
  path: '/pricing/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetDetailsAssetIdRoute = AssetDetailsAssetIdRouteImport.update({
  id: '/asset-details/$assetId',
  path: '/asset-details/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-asset': typeof CreateAssetRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/market-settings': typeof MarketSettingsRoute
  '/order-resolution': typeof OrderResolutionRoute
  '/settings': typeof SettingsRoute
  '/asset-details/$assetId': typeof AssetDetailsAssetIdRoute
  '/pricing/$assetId': typeof PricingAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-asset': typeof CreateAssetRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/market-settings': typeof MarketSettingsRoute
  '/order-resolution': typeof OrderResolutionRoute
  '/settings': typeof SettingsRoute
  '/asset-details/$assetId': typeof AssetDetailsAssetIdRoute
  '/pricing/$assetId': typeof PricingAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-asset': typeof CreateAssetRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/market-settings': typeof MarketSettingsRoute
  '/order-resolution': typeof OrderResolutionRoute
  '/settings': typeof SettingsRoute
  '/asset-details/$assetId': typeof AssetDetailsAssetIdRoute
  '/pricing/$assetId': typeof PricingAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-asset'
    | '/dashboard'
    | '/inventory'
    | '/market-settings'
    | '/order-resolution'
    | '/settings'
    | '/asset-details/$assetId'
    | '/pricing/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-asset'
    | '/dashboard'
    | '/inventory'
    | '/market-settings'
    | '/order-resolution'
    | '/settings'
    | '/asset-details/$assetId'
    | '/pricing/$assetId'
  id:
    | '__root__'
    | '/'
    | '/create-asset'
    | '/dashboard'
    | '/inventory'
    | '/market-settings'
    | '/order-resolution'
    | '/settings'
    | '/asset-details/$assetId'
    | '/pricing/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateAssetRoute: typeof CreateAssetRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  MarketSettingsRoute: typeof MarketSettingsRoute
  OrderResolutionRoute: typeof OrderResolutionRoute
  SettingsRoute: typeof SettingsRoute
  AssetDetailsAssetIdRoute: typeof AssetDetailsAssetIdRoute
  PricingAssetIdRoute: typeof PricingAssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-resolution': {
      id: '/order-resolution'
      path: '/order-resolution'
      fullPath: '/order-resolution'
      preLoaderRoute: typeof OrderResolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-settings': {
      id: '/market-settings'
      path: '/market-settings'
      fullPath: '/market-settings'
      preLoaderRoute: typeof MarketSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-asset': {
      id: '/create-asset'
      path: '/create-asset'
      fullPath: '/create-asset'
      preLoaderRoute: typeof CreateAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/$assetId': {
      id: '/pricing/$assetId'
      path: '/pricing/$assetId'
      fullPath: '/pricing/$assetId'
      preLoaderRoute: typeof PricingAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-details/$assetId': {
      id: '/asset-details/$assetId'
      path: '/asset-details/$assetId'
      fullPath: '/asset-details/$assetId'
      preLoaderRoute: typeof AssetDetailsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateAssetRoute: CreateAssetRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  MarketSettingsRoute: MarketSettingsRoute,
  OrderResolutionRoute: OrderResolutionRoute,
  SettingsRoute: SettingsRoute,
  AssetDetailsAssetIdRoute: AssetDetailsAssetIdRoute,
  PricingAssetIdRoute: PricingAssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
