/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KycIndexRouteImport } from './routes/kyc/index'
import { Route as KycUploadRouteImport } from './routes/kyc/upload'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KycIndexRoute = KycIndexRouteImport.update({
  id: '/kyc/',
  path: '/kyc/',
  getParentRoute: () => rootRouteImport,
} as any)
const KycUploadRoute = KycUploadRouteImport.update({
  id: '/kyc/upload',
  path: '/kyc/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/register': typeof RegisterRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/kyc/upload': typeof KycUploadRoute
  '/kyc/': typeof KycIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/register': typeof RegisterRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/kyc/upload': typeof KycUploadRoute
  '/kyc': typeof KycIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/register': typeof RegisterRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/kyc/upload': typeof KycUploadRoute
  '/kyc/': typeof KycIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/callback'
    | '/dashboard'
    | '/deposit'
    | '/register'
    | '/transactions'
    | '/withdraw'
    | '/kyc/upload'
    | '/kyc/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/callback'
    | '/dashboard'
    | '/deposit'
    | '/register'
    | '/transactions'
    | '/withdraw'
    | '/kyc/upload'
    | '/kyc'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/callback'
    | '/dashboard'
    | '/deposit'
    | '/register'
    | '/transactions'
    | '/withdraw'
    | '/kyc/upload'
    | '/kyc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CallbackRoute: typeof CallbackRoute
  DashboardRoute: typeof DashboardRoute
  DepositRoute: typeof DepositRoute
  RegisterRoute: typeof RegisterRoute
  TransactionsRoute: typeof TransactionsRoute
  WithdrawRoute: typeof WithdrawRoute
  KycUploadRoute: typeof KycUploadRoute
  KycIndexRoute: typeof KycIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc/': {
      id: '/kyc/'
      path: '/kyc'
      fullPath: '/kyc/'
      preLoaderRoute: typeof KycIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc/upload': {
      id: '/kyc/upload'
      path: '/kyc/upload'
      fullPath: '/kyc/upload'
      preLoaderRoute: typeof KycUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CallbackRoute: CallbackRoute,
  DashboardRoute: DashboardRoute,
  DepositRoute: DepositRoute,
  RegisterRoute: RegisterRoute,
  TransactionsRoute: TransactionsRoute,
  WithdrawRoute: WithdrawRoute,
  KycUploadRoute: KycUploadRoute,
  KycIndexRoute: KycIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
