name: Bug Report
description: Report a non-security sensitive bug in fineract-apps
labels: ["kind/bug", "status/triage"]
body:
  - type: checkboxes
    attributes:
      label: Before reporting an issue
      description: |
        Please search to see if the issue is already reported, and try to reproduce the issue on the latest release.

        Any reported issues must be reproducible in the [latest](https://github.com/ADORSYS-GIS/fineract-apps/releases/latest) or [nightly](https://github.com/ADORSYS-GIS/fineract-apps/releases/nightly) version of fineract-apps.

        **⚠️ Failing to follow these guidelines may result in your issue being closed without action. ⚠️**
      options:
        - label: I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.
          required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Affected area
      options:
        -
        - account-manager-app
        - accounting-app
        - admin-app
        - branch-manager-app
        - cashier-app
        - reporting-app
        - user-sync-service
        - i18n
        - fineract-api
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what the problem is.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of fineract-apps are you running?
    validations:
      required: true
  - type: checkboxes
    id: regression
    attributes:
      label: Regression
      description: Was the issue introduced only after upgrading fineract-apps, and it worked as expected in the past?
      options:
        - label: The issue is a regression
  - type: textarea
    id: behaviorExpected
    attributes:
      label: Expected behavior
      description: Describe the expected behavior clearly and concisely.
    validations:
      required: true
  - type: textarea
    id: behaviorActual
    attributes:
      label: Actual behavior
      description: Describe the actual behavior clearly and concisely.
    validations:
      required: true
  - type: textarea
    id: reproducer
    attributes:
      label: How to Reproduce?
      description: Provide clear and concise steps to reproduce the problem.
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority of this bug?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Add logs to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: Links? References? Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
