/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepaymentIndexRouteImport } from './routes/repayment/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ApprovalQueueIndexRouteImport } from './routes/approval-queue/index'
import { Route as RepaymentLoanIdRouteImport } from './routes/repayment/$loanId'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as JournalEntriesEntryIdIndexRouteImport } from './routes/journal-entries/$entryId/index'
import { Route as ApprovalQueueAuditIdIndexRouteImport } from './routes/approval-queue/$auditId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepaymentIndexRoute = RepaymentIndexRouteImport.update({
  id: '/repayment/',
  path: '/repayment/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalQueueIndexRoute = ApprovalQueueIndexRouteImport.update({
  id: '/approval-queue/',
  path: '/approval-queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepaymentLoanIdRoute = RepaymentLoanIdRouteImport.update({
  id: '/repayment/$loanId',
  path: '/repayment/$loanId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalEntriesEntryIdIndexRoute =
  JournalEntriesEntryIdIndexRouteImport.update({
    id: '/journal-entries/$entryId/',
    path: '/journal-entries/$entryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApprovalQueueAuditIdIndexRoute =
  ApprovalQueueAuditIdIndexRouteImport.update({
    id: '/approval-queue/$auditId/',
    path: '/approval-queue/$auditId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/repayment/$loanId': typeof RepaymentLoanIdRoute
  '/approval-queue': typeof ApprovalQueueIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/repayment': typeof RepaymentIndexRoute
  '/approval-queue/$auditId': typeof ApprovalQueueAuditIdIndexRoute
  '/journal-entries/$entryId': typeof JournalEntriesEntryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/repayment/$loanId': typeof RepaymentLoanIdRoute
  '/approval-queue': typeof ApprovalQueueIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/repayment': typeof RepaymentIndexRoute
  '/approval-queue/$auditId': typeof ApprovalQueueAuditIdIndexRoute
  '/journal-entries/$entryId': typeof JournalEntriesEntryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/repayment/$loanId': typeof RepaymentLoanIdRoute
  '/approval-queue/': typeof ApprovalQueueIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/repayment/': typeof RepaymentIndexRoute
  '/approval-queue/$auditId/': typeof ApprovalQueueAuditIdIndexRoute
  '/journal-entries/$entryId/': typeof JournalEntriesEntryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients/$clientId'
    | '/repayment/$loanId'
    | '/approval-queue'
    | '/dashboard'
    | '/repayment'
    | '/approval-queue/$auditId'
    | '/journal-entries/$entryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients/$clientId'
    | '/repayment/$loanId'
    | '/approval-queue'
    | '/dashboard'
    | '/repayment'
    | '/approval-queue/$auditId'
    | '/journal-entries/$entryId'
  id:
    | '__root__'
    | '/'
    | '/clients/$clientId'
    | '/repayment/$loanId'
    | '/approval-queue/'
    | '/dashboard/'
    | '/repayment/'
    | '/approval-queue/$auditId/'
    | '/journal-entries/$entryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  RepaymentLoanIdRoute: typeof RepaymentLoanIdRoute
  ApprovalQueueIndexRoute: typeof ApprovalQueueIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  RepaymentIndexRoute: typeof RepaymentIndexRoute
  ApprovalQueueAuditIdIndexRoute: typeof ApprovalQueueAuditIdIndexRoute
  JournalEntriesEntryIdIndexRoute: typeof JournalEntriesEntryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repayment/': {
      id: '/repayment/'
      path: '/repayment'
      fullPath: '/repayment'
      preLoaderRoute: typeof RepaymentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-queue/': {
      id: '/approval-queue/'
      path: '/approval-queue'
      fullPath: '/approval-queue'
      preLoaderRoute: typeof ApprovalQueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repayment/$loanId': {
      id: '/repayment/$loanId'
      path: '/repayment/$loanId'
      fullPath: '/repayment/$loanId'
      preLoaderRoute: typeof RepaymentLoanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal-entries/$entryId/': {
      id: '/journal-entries/$entryId/'
      path: '/journal-entries/$entryId'
      fullPath: '/journal-entries/$entryId'
      preLoaderRoute: typeof JournalEntriesEntryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-queue/$auditId/': {
      id: '/approval-queue/$auditId/'
      path: '/approval-queue/$auditId'
      fullPath: '/approval-queue/$auditId'
      preLoaderRoute: typeof ApprovalQueueAuditIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  RepaymentLoanIdRoute: RepaymentLoanIdRoute,
  ApprovalQueueIndexRoute: ApprovalQueueIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  RepaymentIndexRoute: RepaymentIndexRoute,
  ApprovalQueueAuditIdIndexRoute: ApprovalQueueAuditIdIndexRoute,
  JournalEntriesEntryIdIndexRoute: JournalEntriesEntryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
