/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FundRouteImport } from './routes/fund'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffAssignRouteImport } from './routes/staff.assign'
import { Route as FundsSettleRouteImport } from './routes/funds.settle'
import { Route as FundsAllocateRouteImport } from './routes/funds.allocate'
import { Route as CreateAccountRouteImport } from './routes/create.account'
import { Route as CreateAccountSavingsRouteImport } from './routes/create.account.savings'
import { Route as CreateAccountLoanRouteImport } from './routes/create.account.loan'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FundRoute = FundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAssignRoute = StaffAssignRouteImport.update({
  id: '/staff/assign',
  path: '/staff/assign',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsSettleRoute = FundsSettleRouteImport.update({
  id: '/funds/settle',
  path: '/funds/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsAllocateRoute = FundsAllocateRouteImport.update({
  id: '/funds/allocate',
  path: '/funds/allocate',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create/account',
  path: '/create/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountSavingsRoute = CreateAccountSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => CreateAccountRoute,
} as any)
const CreateAccountLoanRoute = CreateAccountLoanRouteImport.update({
  id: '/loan',
  path: '/loan',
  getParentRoute: () => CreateAccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/dashboard': typeof DashboardRoute
  '/fund': typeof FundRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/create/account': typeof CreateAccountRouteWithChildren
  '/funds/allocate': typeof FundsAllocateRoute
  '/funds/settle': typeof FundsSettleRoute
  '/staff/assign': typeof StaffAssignRoute
  '/create/account/loan': typeof CreateAccountLoanRoute
  '/create/account/savings': typeof CreateAccountSavingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/dashboard': typeof DashboardRoute
  '/fund': typeof FundRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/create/account': typeof CreateAccountRouteWithChildren
  '/funds/allocate': typeof FundsAllocateRoute
  '/funds/settle': typeof FundsSettleRoute
  '/staff/assign': typeof StaffAssignRoute
  '/create/account/loan': typeof CreateAccountLoanRoute
  '/create/account/savings': typeof CreateAccountSavingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/dashboard': typeof DashboardRoute
  '/fund': typeof FundRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/create/account': typeof CreateAccountRouteWithChildren
  '/funds/allocate': typeof FundsAllocateRoute
  '/funds/settle': typeof FundsSettleRoute
  '/staff/assign': typeof StaffAssignRoute
  '/create/account/loan': typeof CreateAccountLoanRoute
  '/create/account/savings': typeof CreateAccountSavingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branches'
    | '/dashboard'
    | '/fund'
    | '/login'
    | '/reports'
    | '/settings'
    | '/create/account'
    | '/funds/allocate'
    | '/funds/settle'
    | '/staff/assign'
    | '/create/account/loan'
    | '/create/account/savings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branches'
    | '/dashboard'
    | '/fund'
    | '/login'
    | '/reports'
    | '/settings'
    | '/create/account'
    | '/funds/allocate'
    | '/funds/settle'
    | '/staff/assign'
    | '/create/account/loan'
    | '/create/account/savings'
  id:
    | '__root__'
    | '/'
    | '/branches'
    | '/dashboard'
    | '/fund'
    | '/login'
    | '/reports'
    | '/settings'
    | '/create/account'
    | '/funds/allocate'
    | '/funds/settle'
    | '/staff/assign'
    | '/create/account/loan'
    | '/create/account/savings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BranchesRoute: typeof BranchesRoute
  DashboardRoute: typeof DashboardRoute
  FundRoute: typeof FundRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  CreateAccountRoute: typeof CreateAccountRouteWithChildren
  FundsAllocateRoute: typeof FundsAllocateRoute
  FundsSettleRoute: typeof FundsSettleRoute
  StaffAssignRoute: typeof StaffAssignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund': {
      id: '/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof FundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/assign': {
      id: '/staff/assign'
      path: '/staff/assign'
      fullPath: '/staff/assign'
      preLoaderRoute: typeof StaffAssignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds/settle': {
      id: '/funds/settle'
      path: '/funds/settle'
      fullPath: '/funds/settle'
      preLoaderRoute: typeof FundsSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds/allocate': {
      id: '/funds/allocate'
      path: '/funds/allocate'
      fullPath: '/funds/allocate'
      preLoaderRoute: typeof FundsAllocateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/account': {
      id: '/create/account'
      path: '/create/account'
      fullPath: '/create/account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/account/savings': {
      id: '/create/account/savings'
      path: '/savings'
      fullPath: '/create/account/savings'
      preLoaderRoute: typeof CreateAccountSavingsRouteImport
      parentRoute: typeof CreateAccountRoute
    }
    '/create/account/loan': {
      id: '/create/account/loan'
      path: '/loan'
      fullPath: '/create/account/loan'
      preLoaderRoute: typeof CreateAccountLoanRouteImport
      parentRoute: typeof CreateAccountRoute
    }
  }
}

interface CreateAccountRouteChildren {
  CreateAccountLoanRoute: typeof CreateAccountLoanRoute
  CreateAccountSavingsRoute: typeof CreateAccountSavingsRoute
}

const CreateAccountRouteChildren: CreateAccountRouteChildren = {
  CreateAccountLoanRoute: CreateAccountLoanRoute,
  CreateAccountSavingsRoute: CreateAccountSavingsRoute,
}

const CreateAccountRouteWithChildren = CreateAccountRoute._addFileChildren(
  CreateAccountRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BranchesRoute: BranchesRoute,
  DashboardRoute: DashboardRoute,
  FundRoute: FundRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  CreateAccountRoute: CreateAccountRouteWithChildren,
  FundsAllocateRoute: FundsAllocateRoute,
  FundsSettleRoute: FundsSettleRoute,
  StaffAssignRoute: StaffAssignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
