package com.adorsys.fineract.asset.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;

/**
 * Aggregated platform-wide metrics returned by the admin dashboard endpoint
 * ({@code GET /admin/dashboard}). Gives operators a live snapshot of asset health,
 * trading activity, order anomalies, and reconciliation status across the entire
 * asset-service. All counts are computed at query time — no caching layer.
 */
@Schema(description = "Aggregated admin dashboard summary with platform-wide metrics.")
public record AdminDashboardResponse(
    /** Counts of assets broken down by their current lifecycle status. */
    AssetMetrics assets,
    /** Rolling 24-hour trading activity across all active assets. */
    TradingMetrics trading,
    /** Counts of orders in anomalous states that may require operator attention. */
    OrderHealthMetrics orders,
    /** Open reconciliation report counts, indicating outstanding discrepancies. */
    ReconMetrics reconciliation,
    /**
     * Number of distinct users who hold at least one unit of any asset.
     * Calculated from the custodial inventory table, not from Keycloak sessions.
     */
    long activeInvestors
) {

    /**
     * Breakdown of all assets by lifecycle status. Each count is mutually exclusive —
     * an asset appears in exactly one bucket. Use these counts to gauge platform health
     * and identify how many assets need operator action (e.g. PENDING awaiting activation).
     */
    public record AssetMetrics(
        /** Total number of assets ever created on the platform, regardless of status. */
        long total,
        /** Assets currently live and open for trading (status = ACTIVE). */
        long active,
        /** Assets whose trading has been temporarily suspended by an admin (status = HALTED). */
        long halted,
        /** Assets awaiting admin activation (status = PENDING). */
        long pending,
        /**
         * Assets in the delisting grace period — BUY orders are blocked but SELL orders
         * are still accepted to allow holders to exit (status = DELISTING).
         */
        long delisting,
        /** Bond assets that have reached their maturity date; no further trading is allowed (status = MATURED). */
        long matured,
        /** Assets permanently removed from trading (status = DELISTED). */
        long delisted
    ) {}

    /**
     * Rolling 24-hour trading statistics across all assets. The window is computed from
     * the current instant minus 24 hours, not aligned to a calendar day.
     */
    public record TradingMetrics(
        /** Total number of completed trades (filled orders) in the past 24 hours. */
        long tradeCount24h,
        /** Aggregate XAF value of all BUY orders filled in the past 24 hours. */
        BigDecimal buyVolume24h,
        /** Aggregate XAF value of all SELL orders filled in the past 24 hours. */
        BigDecimal sellVolume24h,
        /** Number of distinct users who placed at least one trade in the past 24 hours. */
        long activeTraders24h
    ) {}

    /**
     * Counts of orders currently in states that may require manual operator intervention.
     * These are orders that did not complete normally and are surfaced here to prompt action.
     */
    public record OrderHealthMetrics(
        /**
         * Orders in a state where Fineract and the asset ledger are out of sync —
         * units may have moved on one side but not the other.
         */
        long needsReconciliation,
        /** Orders that terminated with a FAILED status due to a processing error. */
        long failed,
        /** Orders that were resolved manually by an admin rather than the normal settlement flow. */
        long manuallyClosed
    ) {}

    /**
     * Summary of open reconciliation reports generated by the scheduled reconciliation job.
     * A non-zero {@code criticalOpen} count should be investigated immediately as it indicates
     * a confirmed discrepancy between Fineract balances and the asset ledger.
     */
    public record ReconMetrics(
        /** Total number of reconciliation reports not yet resolved (open status). */
        long openReports,
        /** Open reports flagged as CRITICAL — confirmed balance mismatches requiring urgent action. */
        long criticalOpen,
        /** Open reports flagged as WARNING — minor anomalies that should be reviewed but are not urgent. */
        long warningOpen
    ) {}
}
