package com.adorsys.fineract.asset.dto;

import java.time.Instant;

/**
 * A single in-app notification delivered to a user.
 *
 * <p>Returned as a list by {@code GET /api/notifications} (paginated, newest first)
 * and individually by {@code GET /api/notifications/{id}}.
 * Notifications are generated by the system when platform events occur (trades filled,
 * coupons paid, asset status changes, etc.) and are scoped to a specific user.
 *
 * <p>Unread notifications are counted by {@code GET /api/notifications/unread-count}
 * and marked read via {@code POST /api/notifications/{id}/read} or
 * {@code POST /api/notifications/read-all}.
 */
public record NotificationResponse(

    /** Database primary key of this notification record. Stable identifier for mark-read calls. */
    Long id,

    /**
     * Machine-readable event category, matching a key in {@link NotificationPreferencesResponse}.
     * Examples: {@code "TRADE_EXECUTED"}, {@code "COUPON_PAID"}, {@code "ASSET_STATUS_CHANGED"}.
     * Clients can use this to route the notification to a relevant screen or display a
     * category-specific icon.
     */
    String eventType,

    /**
     * Short, human-readable notification headline, e.g. "Order filled: 10 BRVM-BTA purchased".
     * Suitable for display in a notification banner or list item.
     */
    String title,

    /**
     * Full notification body with additional detail, e.g. "You bought 10 units of BRVM Treasury
     * Bond at 9 800 XAF each. Total: 98 000 XAF.". May be multi-sentence but is not HTML.
     */
    String body,

    /**
     * Identifier of the entity that triggered this notification, e.g. an order ID, asset ID,
     * or payment ID. Combined with {@code referenceType}, allows the client to deep-link to
     * the relevant detail screen. Null when no specific entity is associated.
     */
    String referenceId,

    /**
     * Type of the entity identified by {@code referenceId}, e.g. {@code "ORDER"},
     * {@code "ASSET"}, or {@code "PAYMENT"}. Null when {@code referenceId} is null.
     */
    String referenceType,

    /**
     * Whether the user has acknowledged this notification.
     * {@code false} on creation; {@code true} after a mark-read call.
     * Used to drive the unread badge count in the UI.
     */
    boolean read,

    /**
     * Timestamp when this notification was created, in UTC.
     * Use for display ("2 minutes ago") and for sorting notifications newest-first.
     */
    Instant createdAt

) {}
