package com.adorsys.fineract.asset.dto;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Full order detail record returned by the admin order detail endpoint.
 *
 * <p>Returned by {@code GET /api/admin/orders/{orderId}}. Contains every field needed
 * for an admin to investigate or resolve an order, including operational metadata such as
 * the idempotency key, Fineract batch ID, and optimistic-lock version.
 *
 * <p>For the lighter summary list used on the admin orders table, see {@link AdminOrderResponse}.
 * For the user-facing order view (no admin-only fields), see {@link OrderResponse}.
 *
 * <p>All monetary amounts are in the settlement currency (XAF).
 */
public record OrderDetailResponse(

    /** Unique order identifier (UUID string). Stable across all status transitions. */
    String orderId,

    /** Internal asset identifier. Cross-reference with the asset catalogue for full asset detail. */
    String assetId,

    /** Ticker symbol of the traded asset at the time the order was placed, e.g. "BRVM-BTA". */
    String symbol,

    /** Human-readable asset name at the time the order was placed. */
    String assetName,

    /**
     * Direction of the trade: BUY (user buys units, cash leaves their account) or
     * SELL (user sells units, cash enters their account).
     */
    TradeSide side,

    /**
     * Number of asset units involved in the order.
     * On BUY: units to credit to the user's position.
     * On SELL: units to debit from the user's position.
     */
    BigDecimal units,

    /**
     * Execution price per unit at the time the order was quoted and confirmed, in XAF.
     * BUY orders use the ask price; SELL orders use the bid price.
     * Locked at quote time — not updated if the market price moves before execution.
     */
    BigDecimal pricePerUnit,

    /**
     * Gross trade value before fees: {@code units × pricePerUnit}, in XAF.
     * For BUY: the total cash the user committed (before fee deduction).
     * For SELL: the gross proceeds before fee deduction.
     */
    BigDecimal totalAmount,

    /**
     * Platform service fee charged on this order, in XAF.
     * Deducted from the user on BUY; deducted from proceeds on SELL.
     * The net cash impact on the user is {@code totalAmount ± fee} depending on direction.
     */
    BigDecimal fee,

    /**
     * LP spread amount earned on this order, in XAF.
     * Formula: {@code (askPrice - bidPrice) × units}.
     * Credited to the LP's spread income account (LSPD) when the order is filled.
     */
    BigDecimal spreadAmount,

    /**
     * Current lifecycle status of the order.
     * See {@link OrderStatus} for the full state machine and transition rules.
     */
    OrderStatus status,

    /**
     * Human-readable explanation of why the order failed or was rejected.
     * Null when the order is in any non-terminal status or when it succeeded (FILLED).
     * Set at execution time for FAILED orders and at validation time for REJECTED orders.
     */
    String failureReason,

    /**
     * External user identifier from the identity provider (e.g. Keycloak subject claim).
     * Used to cross-reference the order with the user's identity without exposing the
     * internal Fineract client ID.
     */
    String userExternalId,

    /**
     * Internal Fineract client ID of the user who placed the order.
     * Used to look up the user's savings accounts directly in Fineract.
     */
    Long userId,

    /**
     * Client-supplied idempotency key used to deduplicate order submissions.
     * If a client submits the same key twice, the second request returns the existing order
     * rather than creating a duplicate. Generated by the frontend and stored here for
     * audit and debugging purposes.
     */
    String idempotencyKey,

    /**
     * Fineract batch transfer ID associated with the Fineract journal entries for this order.
     * Null until the order moves to EXECUTING. Used by admins to reconcile asset-service
     * records against Fineract transaction logs when investigating discrepancies.
     */
    String fineractBatchId,

    /**
     * Optimistic-lock version counter for this order record.
     * Increments on every status update. Used internally to prevent concurrent modification;
     * exposed here so admins can identify orders that have been updated many times.
     */
    Long version,

    /**
     * Username or identifier of the admin who manually resolved this order.
     * Null unless the order is in MANUALLY_CLOSED status.
     */
    String resolvedBy,

    /**
     * Timestamp when an admin manually closed this order, in UTC.
     * Null unless the order is in MANUALLY_CLOSED status.
     */
    Instant resolvedAt,

    /**
     * Timestamp when the order was first created (quote issued), in UTC.
     */
    Instant createdAt,

    /**
     * Timestamp of the most recent status update to this order, in UTC.
     * Changes on every transition: QUOTED → PENDING → EXECUTING → FILLED/FAILED/etc.
     */
    Instant updatedAt

) {
}
