package com.adorsys.fineract.asset.dto;

import java.math.BigDecimal;
import java.util.List;

/**
 * Treasury rebalancing proposal generated by the admin rebalance engine.
 *
 * <p>Returned by {@code GET /api/admin/treasury/rebalance-proposal}. The proposal analyses the
 * current state of all settlement accounts (bank accounts and mobile money wallets) against
 * the outstanding obligations to LPs, tax authorities, and the platform fee pool, then produces
 * a phased sequence of transfer instructions that would bring all accounts into a compliant state.
 *
 * <p>All monetary amounts are in the settlement currency (XAF). The {@code feasible} flag
 * indicates whether the available liquid balance is sufficient to cover all obligations without
 * a shortfall. When {@code feasible} is {@code false}, {@code shortfall} describes how much
 * additional funding is needed before the rebalance can be executed.
 *
 * <p>The admin reviews this proposal and then triggers execution via
 * {@code POST /api/admin/treasury/execute-rebalance}, passing the proposed transfers from
 * {@link ExecuteRebalanceRequest}.
 */
public record RebalanceProposalResponse(

    /**
     * Total amount owed to all LP clients across all assets, in XAF.
     * Represents the sum of all unsettled LP obligations (spread income, buyback premiums)
     * that must be transferred out of the trust account to LP savings accounts.
     */
    BigDecimal totalLpOwed,

    /**
     * Total withholding tax owed to the tax authority, in XAF.
     * Accumulated from tax amounts withheld on LP income, coupon payments, and capital gains.
     * Must be remitted to the government's designated account before the reserve is clean.
     */
    BigDecimal totalTaxOwed,

    /**
     * Total platform service fees owed and not yet swept to the platform fee account, in XAF.
     * Accumulated from the fee amounts deducted at order execution time across all filled orders.
     */
    BigDecimal totalFeesOwed,

    /**
     * Total cash that must flow out of the trust/reserve accounts to settle all obligations, in XAF.
     * Sum of {@code totalLpOwed + totalTaxOwed + totalFeesOwed}.
     * This is the minimum outflow needed to achieve a clean, obligation-free treasury state.
     */
    BigDecimal totalOutflowNeeded,

    /**
     * Current balance of the UBA (United Bank for Africa) settlement account, in XAF.
     * One of the two primary bank settlement channels used for LP and tax payments.
     */
    BigDecimal ubaCurrentBalance,

    /**
     * Current balance of the Afriland First Bank settlement account, in XAF.
     * The second primary bank settlement channel, used alongside UBA for large transfers.
     */
    BigDecimal afrilandCurrentBalance,

    /**
     * Amount needed in the UBA account to cover its share of the total outflow, in XAF.
     * The rebalance engine splits obligations across settlement channels based on capacity.
     * Zero if UBA already holds sufficient funds or is not assigned obligations in this proposal.
     */
    BigDecimal needInUba,

    /**
     * Amount needed in the Afriland account to cover its share of the total outflow, in XAF.
     * Zero if Afriland already holds sufficient funds or is not assigned obligations in this proposal.
     */
    BigDecimal needInAfriland,

    /**
     * Current total balance across all MTN Mobile Money (MoMo) wallets, in XAF.
     * Mobile money wallets are used to receive payments from users who pay via MoMo.
     */
    BigDecimal momoBalance,

    /**
     * Current total balance across all Orange Money wallets, in XAF.
     * Orange Money wallets receive user payments via the Orange mobile money network.
     */
    BigDecimal orangeBalance,

    /**
     * Liquid MoMo balance available for rebalancing transfers, in XAF.
     * May differ from {@code momoBalance} if a minimum wallet reserve must be maintained.
     * This is the amount the rebalance engine can freely move out of MoMo wallets.
     */
    BigDecimal momoAvailable,

    /**
     * Liquid Orange Money balance available for rebalancing transfers, in XAF.
     * Same reserve logic as {@code momoAvailable} but for Orange Money wallets.
     */
    BigDecimal orangeAvailable,

    /**
     * Sum of {@code momoAvailable} and {@code orangeAvailable}, in XAF.
     * The total mobile money liquidity the rebalance engine can mobilise toward obligations.
     */
    BigDecimal totalMobileAvailable,

    /**
     * Minimum reserve ratio that must remain in the combined settlement pool after rebalancing,
     * expressed as a percentage (e.g. {@code 10.0} means 10% must be kept as a buffer).
     * The rebalance engine constrains transfers so that the post-rebalance balance stays
     * above this percentage of the total pool.
     */
    BigDecimal reservePercent,

    /**
     * Whether the available liquid balance across all channels is sufficient to cover
     * {@code totalOutflowNeeded} while maintaining {@code reservePercent}.
     * {@code true} means the proposal can be executed immediately with current balances.
     * {@code false} means additional funding must be injected before execution.
     */
    boolean feasible,

    /**
     * Funding gap between what is available and what is needed, in XAF.
     * Zero when {@code feasible} is {@code true}. When positive, this is the amount an admin
     * must arrange to deposit (from an external funding source) before the rebalance can proceed.
     */
    BigDecimal shortfall,

    /**
     * Ordered list of proposed inter-account transfers that would execute the rebalance.
     * Transfers are grouped by phase: phase 1 typically moves mobile money funds to bank accounts;
     * phase 2 sweeps bank accounts to LP, tax, and fee destinations.
     * The admin executes these sequentially via the Fineract transfer API or manually.
     */
    List<ProposedTransfer> transfers

) {

    /**
     * A single proposed inter-account transfer as part of the rebalance plan.
     * Each transfer moves a specific amount between two GL-coded accounts in a defined phase.
     */
    public record ProposedTransfer(

        /**
         * Execution phase number (1, 2, 3, …). Transfers within the same phase can be executed
         * in parallel; all phase N transfers must complete before phase N+1 begins.
         */
        int phase,

        /**
         * Settlement channel type for this transfer.
         * Examples: {@code "BANK"}, {@code "MOMO"}, {@code "ORANGE_MONEY"}.
         * Determines which Fineract savings account or external API to use.
         */
        String settlementType,

        /**
         * GL account code of the source account from which funds will be debited.
         * Matches a GL code in the Fineract chart of accounts used by the asset service.
         */
        String sourceGlCode,

        /** Human-readable name of the source account, e.g. "MoMo Trust Account - MTN". */
        String sourceName,

        /**
         * GL account code of the destination account to which funds will be credited.
         * Matches a GL code in the Fineract chart of accounts.
         */
        String destinationGlCode,

        /** Human-readable name of the destination account, e.g. "UBA Settlement Account". */
        String destinationName,

        /**
         * Amount to transfer from source to destination, in XAF.
         * Always positive. Validated against available balance before the proposal is finalized.
         */
        BigDecimal amount,

        /**
         * Plain-English description of why this transfer is needed, e.g.
         * "Move MoMo liquidity to UBA to cover LP payouts in phase 2".
         * Shown to the admin in the rebalance review UI.
         */
        String description,

        /**
         * Specific manual step the admin should take to execute this transfer,
         * e.g. "Initiate bank transfer from MoMo wallet #3 to UBA account 0123456789".
         * Null for fully automated transfers that the system handles via Fineract API calls.
         */
        String adminAction

    ) {}
}
