name: Build and Push Account manager App Image

on:
  push:
    branches:
      - 7-account-manager-app
    paths:
       - 'frontend/account-manager-app/**'
       - '.github/workflows/deploy-account-manager.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: adorsys-gis/fineract-apps/account-manager-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./frontend/account-manager-app/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
