name: Build and Push Cashier App Image

on:
  push:
    branches:
      - feat/cashier-app-transactions-ui-ux
    paths:
      - 'fineract-apps/frontend/cashier-app/**'
      - 'fineract-apps/.github/workflows/deploy-cashier-app.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: adorsys-gis/fineract-apps/cashier-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./fineract-apps/frontend/cashier-app/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}